//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edgar.GeneradorNumerosPrimos.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud
    {
        public int id { get; set; }
        public int inicio { get; set; }
        public int fin { get; set; }
        public Nullable<int> cantidad { get; set; }
    }
}
